image: archlinux
packages:
  - rustup
sources:
  - https://github.com/mellium/xmpp-addr.git
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd xmpp-addr/
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd xmpp-addr/
      cargo test
  - nightly: |
      rustup default nightly
      cd xmpp-addr/
      cargo test --features=try_from,ascii_ctype
