image: atlassianlabs/buildpack-deps-rust
clone:
  depth: 1

pipelines:
  default:
    - step:
        script:
          - echo "Update Rustup"          ; rustup self update
          - echo "Update Rust toolchains" ; rustup update
          - echo "Use nightly toolchain"  ; rustup default nightly
          - echo "Show Rust toolchain"    ; rustup show && rustc --version
          - echo "Run unit tests"         ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
          - echo "Building docs"          ; cargo doc --all-features --release
          - echo "Packaging crate"        ; cargo package
  tags:
    v*:
      - step:
          script:
            - echo "Update Rustup"          ; rustup self update
            - echo "Update Rust toolchains" ; rustup update
            - echo "Use nightly toolchain"  ; rustup default nightly
            - echo "Show Rust toolchain"    ; rustup show && rustc --version
            - echo "Run unit tests"         ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
            - echo "Building docs"          ; cargo doc --all-features --release
            - echo "Publishing crate"       ; cargo publish --token ${CARGO_API_KEY}
