[package]
name = "xmpp-jid"
# Remember to bump html_root_url in src/lib.rs as well.
version = "0.3.1"
authors = ["Sam Whited <sam@samwhited.com>"]
license = "BSD-2-Clause"
description = """
An implementation of the XMPP Address format (Jabber ID) defined in RFC 7622.
"""
repository = "https://bitbucket.org/mellium/xmpp-jid/"
readme = "README.md"
keywords = ["xmpp", "jabber", "jid", "rfc7622", "rfc6120"]
documentation = "https://docs.rs/xmpp-jid"
categories = []

exclude = [
    "bitbucket-pipelines.yml",
]

[features]
default = ["stable", "serde"]

# Use only stable APIs (eg. don't build with TryFrom)
stable = []

[dependencies]
idna = "0.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
