[package]
name = "xmpp-jid"
version = "0.2.3"
authors = ["Sam Whited <sam@samwhited.com>"]
license = "BSD-2-Clause"
description = """
An implementation of the XMPP Address format (Jabber ID) defined in RFC 7622.
Currently only compiles on nightly versions of Rust.
"""
repository = "https://bitbucket.org/mellium/xmpp-jid/"
readme = "README.md"
keywords = ["xmpp", "jabber", "jid", "rfc7622", "rfc6120"]
documentation = "https://docs.rs/xmpp-jid"
categories = []

exclude = [
    "bitbucket-pipelines.yml",
]

[dependencies]
idna = "0.1"
