[package]
name = "xmpp"
version = "0.1.0"
authors = ["Sam Whited <sam@samwhited.com>"]
license = "BSD-2-clause"
description = "An implementation of the XMPP Address format (Jabber ID) defined in RFC 7622. Eventually this may become a full XMPP implementation."
repository = "https://bitbucket.org/mellium/xmpp-rs"
readme = "README.md"

[dependencies]
idna = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.1"
