[package]
name = "xmpp-jid"
version = "0.1.1"
authors = ["Sam Whited <sam@samwhited.com>"]
license = "BSD-2-Clause"
description = "An implementation of the XMPP Address format (Jabber ID) defined in RFC 7622."
repository = "https://bitbucket.org/mellium/xmpp-jid-rs"
readme = "README.md"
keywords = ["xmpp", "jabber", "jid", "rfc7622", "rfc6120"]
documentation = "https://docs.rs/xmpp-jid"
categories = []

exclude = [
    "bitbucket-pipelines.yml",
]

[dependencies]
idna = "0.1"
serde = "1.0"
serde_derive = "1.0"
